{{- $pspAvailable := (semverCompare "<1.25-0" (include "common.capabilities.kubeVersion" .)) -}}
{{- if and $pspAvailable  .Values.rbac.pspEnabled }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "capi2argo-cluster-operator.fullname" . }}-psp
  labels: {{ include "capi2argo-cluster-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "capi2argo-cluster-operator.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "capi2argo-cluster-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
